apiVersion: batch/v1
kind: Job
metadata:
  name: testing-map-optimization
spec:
  template:
    metadata:
      name: countdown
    spec:
      containers:
      - name: counter
        image: ubuntu:latest
        command:
         - "bin/bash"
         - "-c"
         - "apt-install osmium-tool"
         - "osmium -h"
         - "for i in 9 8 7 6 5 4 3 2 1 ; do echo $i ; done"
      restartPolicy: Never
